server:
  port: 8091
#  servlet:
#    contextPath: /v1/small-square

spring:
  datasource:
    url: jdbc:mysql://localhost/small_square
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update


appDescription: "Reto plazoletas - ms plazoleta"
appVersion: "1.0.0"

url-base:
  ms-users: http://localhost:8090/v1/users
  ms-messaging: http://localhost:8092/api/v1/messaging

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970 # Una clave secreta fuerte (m√≠nimo 256 bits, codificada en Base64)
