server:
  port: 8091
  servlet:
    contextPath: /v1/small-square

spring:
  datasource:
    url: jdbc:mysql://localhost/small_square
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update


appDescription: "Reto plazoletas - ms plazoleta"
appVersion: "1.0.0"

url-base:
  ms-users: http://localhost:8090/v1/users